name: Pipeline

on:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:

  tests:
    name: Unit And Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21.1'
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-tests-${{ hashFiles('**/go.sum') }}
